/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as BookTokenRouteImport } from './routes/book.$token'
import { Route as AppUpgradeRouteImport } from './routes/_app.upgrade'
import { Route as AppTriageRouteImport } from './routes/_app.triage'
import { Route as AppSystemsRouteImport } from './routes/_app.systems'
import { Route as AppRealtorRouteImport } from './routes/_app.realtor'
import { Route as AppProsRouteImport } from './routes/_app.pros'
import { Route as AppPartnersRouteImport } from './routes/_app.partners'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppProsIdRouteImport } from './routes/_app.pros.$id'
import { Route as AppBookingsIdRouteImport } from './routes/_app.bookings.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicBookingsTokenRouteImport } from './routes/api/public/bookings.$token'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTokenRoute = BookTokenRouteImport.update({
  id: '/book/$token',
  path: '/book/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemsRoute = AppSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => AppRoute,
} as any)
const AppRealtorRoute = AppRealtorRouteImport.update({
  id: '/realtor',
  path: '/realtor',
  getParentRoute: () => AppRoute,
} as any)
const AppProsRoute = AppProsRouteImport.update({
  id: '/pros',
  path: '/pros',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppProsIdRoute = AppProsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProsRoute,
} as any)
const AppBookingsIdRoute = AppBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBookingsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingsTokenRoute = ApiPublicBookingsTokenRouteImport.update({
  id: '/api/public/bookings/$token',
  path: '/api/public/bookings/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/bookings': typeof AppBookingsRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/home': typeof AppHomeRoute
  '/logs': typeof AppLogsRoute
  '/partners': typeof AppPartnersRoute
  '/pros': typeof AppProsRouteWithChildren
  '/realtor': typeof AppRealtorRoute
  '/systems': typeof AppSystemsRoute
  '/triage': typeof AppTriageRoute
  '/upgrade': typeof AppUpgradeRoute
  '/book/$token': typeof BookTokenRoute
  '/r/$code': typeof RCodeRoute
  '/bookings/$id': typeof AppBookingsIdRoute
  '/pros/$id': typeof AppProsIdRoute
  '/api/public/bookings/$token': typeof ApiPublicBookingsTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/bookings': typeof AppBookingsRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/home': typeof AppHomeRoute
  '/logs': typeof AppLogsRoute
  '/partners': typeof AppPartnersRoute
  '/pros': typeof AppProsRouteWithChildren
  '/realtor': typeof AppRealtorRoute
  '/systems': typeof AppSystemsRoute
  '/triage': typeof AppTriageRoute
  '/upgrade': typeof AppUpgradeRoute
  '/book/$token': typeof BookTokenRoute
  '/r/$code': typeof RCodeRoute
  '/bookings/$id': typeof AppBookingsIdRoute
  '/pros/$id': typeof AppProsIdRoute
  '/api/public/bookings/$token': typeof ApiPublicBookingsTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/bookings': typeof AppBookingsRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/pros': typeof AppProsRouteWithChildren
  '/_app/realtor': typeof AppRealtorRoute
  '/_app/systems': typeof AppSystemsRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/book/$token': typeof BookTokenRoute
  '/r/$code': typeof RCodeRoute
  '/_app/bookings/$id': typeof AppBookingsIdRoute
  '/_app/pros/$id': typeof AppProsIdRoute
  '/api/public/bookings/$token': typeof ApiPublicBookingsTokenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/bookings'
    | '/calendar'
    | '/home'
    | '/logs'
    | '/partners'
    | '/pros'
    | '/realtor'
    | '/systems'
    | '/triage'
    | '/upgrade'
    | '/book/$token'
    | '/r/$code'
    | '/bookings/$id'
    | '/pros/$id'
    | '/api/public/bookings/$token'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/bookings'
    | '/calendar'
    | '/home'
    | '/logs'
    | '/partners'
    | '/pros'
    | '/realtor'
    | '/systems'
    | '/triage'
    | '/upgrade'
    | '/book/$token'
    | '/r/$code'
    | '/bookings/$id'
    | '/pros/$id'
    | '/api/public/bookings/$token'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/bookings'
    | '/_app/calendar'
    | '/_app/home'
    | '/_app/logs'
    | '/_app/partners'
    | '/_app/pros'
    | '/_app/realtor'
    | '/_app/systems'
    | '/_app/triage'
    | '/_app/upgrade'
    | '/book/$token'
    | '/r/$code'
    | '/_app/bookings/$id'
    | '/_app/pros/$id'
    | '/api/public/bookings/$token'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  BookTokenRoute: typeof BookTokenRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicBookingsTokenRoute: typeof ApiPublicBookingsTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$token': {
      id: '/book/$token'
      path: '/book/$token'
      fullPath: '/book/$token'
      preLoaderRoute: typeof BookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/systems': {
      id: '/_app/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof AppSystemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/realtor': {
      id: '/_app/realtor'
      path: '/realtor'
      fullPath: '/realtor'
      preLoaderRoute: typeof AppRealtorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pros': {
      id: '/_app/pros'
      path: '/pros'
      fullPath: '/pros'
      preLoaderRoute: typeof AppProsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pros/$id': {
      id: '/_app/pros/$id'
      path: '/$id'
      fullPath: '/pros/$id'
      preLoaderRoute: typeof AppProsIdRouteImport
      parentRoute: typeof AppProsRoute
    }
    '/_app/bookings/$id': {
      id: '/_app/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AppBookingsIdRouteImport
      parentRoute: typeof AppBookingsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/$token': {
      id: '/api/public/bookings/$token'
      path: '/api/public/bookings/$token'
      fullPath: '/api/public/bookings/$token'
      preLoaderRoute: typeof ApiPublicBookingsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppBookingsRouteChildren {
  AppBookingsIdRoute: typeof AppBookingsIdRoute
}

const AppBookingsRouteChildren: AppBookingsRouteChildren = {
  AppBookingsIdRoute: AppBookingsIdRoute,
}

const AppBookingsRouteWithChildren = AppBookingsRoute._addFileChildren(
  AppBookingsRouteChildren,
)

interface AppProsRouteChildren {
  AppProsIdRoute: typeof AppProsIdRoute
}

const AppProsRouteChildren: AppProsRouteChildren = {
  AppProsIdRoute: AppProsIdRoute,
}

const AppProsRouteWithChildren =
  AppProsRoute._addFileChildren(AppProsRouteChildren)

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppProsRoute: typeof AppProsRouteWithChildren
  AppRealtorRoute: typeof AppRealtorRoute
  AppSystemsRoute: typeof AppSystemsRoute
  AppTriageRoute: typeof AppTriageRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppHomeRoute: AppHomeRoute,
  AppLogsRoute: AppLogsRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppProsRoute: AppProsRouteWithChildren,
  AppRealtorRoute: AppRealtorRoute,
  AppSystemsRoute: AppSystemsRoute,
  AppTriageRoute: AppTriageRoute,
  AppUpgradeRoute: AppUpgradeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  BookTokenRoute: BookTokenRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicBookingsTokenRoute: ApiPublicBookingsTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
